steps:
# build and tag container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build . --tag cleaner_app']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker tag cleaner_app:latest eu.gcr.io/${PROJECT_ID}/cleaner_app']

# push it up to Google Cloud Repo
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push eu.gcr.io/${PROJECT_ID}/cleaner_app']

# Install dependencies
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: ["-c", "pip install -r requirements.txt --user"]

# run test
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker run cleaner_app pytest']

# Deploy function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - cleaner
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python39
  - --entry-point=cleaner
  - --min-instances=1
  - --memory=128MB
  - --allow-unauthenticated