steps:
# Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run unit tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"]

# Deploy function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - test_cicd
    - --region=us-central1
    - --source=.
    - --trigger-http
    - --runtime=python39
    - --entry-point=secret_length
    - --min-instances=1
    - --memory=128MB
    - --allow-unauthenticated
    - --set-secrets=ibm-creds=ibm-planning-creds:latest